import {rooms,mode} from './multiplayer.js';

const app=document.querySelector('#app'), toastEl=document.querySelector('#toast');
const faces={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
const cats=[['ones','ones'],['twos','twos'],['threes','threes'],['fours','fours'],['fives','fives'],['sixes','sixes'],['three-kind','three of a kind'],['four-kind','four of a kind'],['full-house','full house'],['small-straight','small straight'],['large-straight','large straight'],['yahtzee','yahtzee'],['chance','chance']];
let me={id:sessionStorage.gayId||crypto.randomUUID(),name:sessionStorage.gayName||''}, room=null, unsubscribe=null, rolling=false;
sessionStorage.gayId=me.id;

let audio;
function sound(type){
  try{
    audio ||= new AudioContext();
    const now=audio.currentTime, gain=audio.createGain(), osc=audio.createOscillator();
    osc.type=type==='roll'?'triangle':'sine'; osc.frequency.setValueAtTime(type==='roll'?95:type==='hold'?390:240,now);
    if(type==='roll')osc.frequency.exponentialRampToValueAtTime(65,now+.14);
    gain.gain.setValueAtTime(type==='roll'?.035:.022,now);gain.gain.exponentialRampToValueAtTime(.0001,now+(type==='roll'?.15:.07));
    osc.connect(gain).connect(audio.destination);osc.start(now);osc.stop(now+(type==='roll'?.16:.08));
  }catch{}
}

function toast(s){toastEl.textContent=s;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1800)}
function code(){const chars='23456789ABCDEFGHJKMNPQRSTUVWXYZ';return Array.from({length:5},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function shell(body){app.innerHTML=`<main class="shell">${body}</main>`}
function landing(){cleanup();shell(`<section class="landing"><div class="brand"><h1>generic asf yahtzee</h1><p>five dice. thirteen rounds. no nonsense.</p><div class="actions"><button class="btn primary" id="create">create room</button><button class="btn" id="join">join room</button></div></div></section>`);$('#create').onclick=()=>nameScreen('create');$('#join').onclick=()=>nameScreen('join')}
function nameScreen(type){shell(`<button class="link-btn back" id="back">← back</button><section class="landing"><form class="form" id="form"><div class="brand"><h1>${type} room</h1><p>${type==='create'?'pick a name and invite someone.':'enter your name and room code.'}</p></div><label>your name<input class="input" id="name" maxlength="18" placeholder="player" value="${esc(me.name)}" required></label>${type==='join'?'<label>room code<input class="input code-input" id="code" maxlength="5" autocomplete="off" required></label>':''}<button class="btn primary">continue</button><div class="error" id="error"></div></form></section>`);$('#back').onclick=landing;$('#form').onsubmit=async e=>{e.preventDefault();me.name=$('#name').value.trim();sessionStorage.gayName=me.name;try{if(type==='create')await createRoom();else await joinRoom($('#code').value.toUpperCase().trim())}catch(err){$('#error').textContent='couldn’t connect. try again.';console.error(err)}}}
async function createRoom(){room={code:code(),host:me.id,status:'lobby',players:{[me.id]:{name:me.name,score:{}}},turn:me.id,dice:[1,1,1,1,1],held:[false,false,false,false,false],rolls:0};await rooms.create(room);watch();lobby()}
async function joinRoom(c){if(!/^[2-9A-HJ-KM-NP-Z]{5}$/.test(c)){return $('#error').textContent='that code doesn’t look right.'}const r=await rooms.get(c);if(!r)return $('#error').textContent='room not found.';if(Object.keys(r.players).length>=2&&!r.players[me.id])return $('#error').textContent='that room is full.';room=r;room.players[me.id]={name:me.name,score:{}};await rooms.save(room);watch();room.status==='game'?game():lobby()}
function watch(){unsubscribe?.();unsubscribe=rooms.subscribe(room.code,next=>{room=next;room.status==='game'?game():lobby()})}
function cleanup(){unsubscribe?.();unsubscribe=null;room=null}
function lobby(){const ps=Object.entries(room.players);shell(`<header class="topbar"><span class="wordmark">generic asf yahtzee</span><span class="status"><i class="dot"></i>${mode}</span></header><section class="lobby"><span class="eyebrow">room</span><div class="room-code">${room.code}</div><div class="copyrow"><span class="eyebrow">share this code</span><button class="btn" id="copy">copy</button></div><span class="eyebrow">players · ${ps.length}/2</span><div class="players">${ps.map(([id,p])=>`<div class="player"><span>${esc(p.name)}</span>${id===room.host?'<span class="badge">host</span>':''}</div>`).join('')}</div>${me.id===room.host?`<button class="btn accent" id="start" ${ps.length<2?'disabled':''}>${ps.length<2?'waiting for someone…':'start game'}</button>`:'<p class="hint">waiting for the host to start…</p>'}</section>`);$('#copy').onclick=()=>navigator.clipboard.writeText(room.code).then(()=>toast('room code copied'));if($('#start'))$('#start').onclick=async()=>{room.status='game';room.turn=room.host;await rooms.save(room)}}
function score(kind,d){const counts=d.reduce((a,n)=>(a[n]=(a[n]||0)+1,a),{}),sum=d.reduce((a,b)=>a+b,0),vals=[...new Set(d)].sort();if(['ones','twos','threes','fours','fives','sixes'].includes(kind)){const n=['ones','twos','threes','fours','fives','sixes'].indexOf(kind)+1;return d.filter(x=>x===n).length*n}if(kind==='three-kind')return Object.values(counts).some(x=>x>=3)?sum:0;if(kind==='four-kind')return Object.values(counts).some(x=>x>=4)?sum:0;if(kind==='full-house')return Object.values(counts).sort().join('')==='23'?25:0;if(kind==='small-straight')return ['1234','2345','3456'].some(x=>x.split('').every(n=>vals.includes(+n)))?30:0;if(kind==='large-straight')return vals.join('')==='12345'||vals.join('')==='23456'?40:0;if(kind==='yahtzee')return Object.values(counts).includes(5)?50:0;return sum}
function total(p){const s=Object.values(p.score||{}).reduce((a,b)=>a+b,0),upper=['ones','twos','threes','fours','fives','sixes'].reduce((a,k)=>a+(p.score?.[k]||0),0);return s+(upper>=63?35:0)}
function die(v,i){return `<div class="die-wrap"><button class="die ${room.held[i]?'held':''} ${rolling?'rolling':''}" data-die="${i}" aria-label="die ${i+1}, ${v}${room.held[i]?', held':''}" ${room.turn!==me.id||!room.rolls||rolling?'disabled':''}>${Array.from({length:9},(_,j)=>faces[v].includes(j)?'<i class="pip"></i>':'<i></i>').join('')}</button>${room.held[i]?'<span class="held-label">held</span>':''}</div>`}
function game(){const entries=Object.entries(room.players),mine=room.players[me.id],active=room.players[room.turn];if(!mine)return;const finished=entries.every(([,p])=>Object.keys(p.score||{}).length===13);if(finished)return endScreen(entries);shell(`<header class="topbar"><span class="wordmark">generic asf yahtzee</span><span class="status"><i class="dot"></i>room ${room.code}</span></header><div class="game game-grid"><section class="play-area"><div class="turnbar"><div><span class="eyebrow">current turn</span><h2>${room.turn===me.id?'your turn':esc(active?.name||'opponent')}</h2></div><div class="versus">${entries.map(([id,p])=>`<span class="mini-player ${id===room.turn?'active':''}">${esc(p.name)} · ${total(p)}</span>`).join('')}</div></div><div class="table"><div class="dice-wrap"><div class="dice-row">${room.dice.map(die).join('')}</div><button class="btn accent" id="roll" ${room.turn!==me.id||room.rolls>=3||rolling?'disabled':''}>${room.rolls?'roll again':'roll dice'}</button><div class="roll-meta">${room.rolls?`roll ${room.rolls} of 3`:'up to 3 rolls'}</div><div class="hint">${room.turn===me.id?(room.rolls?'tap dice to hold · choose a score when ready':'roll all five dice to begin'):'hang tight — the other player is rolling'}</div></div></div></section>${scorecard(mine)}</div>`);document.querySelectorAll('[data-die]').forEach(el=>el.onclick=()=>toggleDie(+el.dataset.die));$('#roll').onclick=roll;document.querySelectorAll('[data-score]').forEach(el=>el.onclick=()=>takeScore(el.dataset.score))}
function scorecard(p){const used=p.score||{};return `<aside class="scorecard"><h2>your scorecard</h2><div class="score-section"><div class="section-label">upper</div>${cats.slice(0,6).map(row).join('')}</div><div class="score-section"><div class="section-label">lower</div>${cats.slice(6).map(row).join('')}</div><div class="total"><span>total</span><span>${total(p)}</span></div></aside>`;function row([k,label]){const done=k in used,avail=room.rolls&&room.turn===me.id&&!done;return `<button class="score-row ${avail?'available':''}" data-score="${k}" ${avail?'':'disabled'}><span>${label}</span><span class="points ${avail?'preview':''}">${done?used[k]:avail?score(k,room.dice):'—'}</span></button>`}}
async function toggleDie(i){room.held[i]=!room.held[i];sound(room.held[i]?'hold':'release');game();await rooms.save(room)}
async function roll(){if(rolling)return;rolling=true;sound('roll');game();const final=room.dice.map((d,i)=>room.held[i]?d:1+Math.floor(Math.random()*6));let ticks=0;const timer=setInterval(()=>{room.dice=room.dice.map((d,i)=>room.held[i]?d:1+Math.floor(Math.random()*6));game();if(++ticks>=7){clearInterval(timer);room.dice=final;room.rolls++;rolling=false;sound('land');game();rooms.save(room)}},75)}
async function takeScore(k){room.players[me.id].score[k]=score(k,room.dice);const ids=Object.keys(room.players),idx=ids.indexOf(me.id);room.turn=ids[(idx+1)%ids.length];room.dice=[1,1,1,1,1];room.held=[false,false,false,false,false];room.rolls=0;await rooms.save(room)}
function endScreen(entries){const sorted=[...entries].sort((a,b)=>total(b[1])-total(a[1])),tie=total(sorted[0][1])===total(sorted[1][1]);shell(`<header class="topbar"><span class="wordmark">generic asf yahtzee</span></header><section class="lobby winner"><span class="eyebrow">game over</span><h2>${tie?'it’s a tie':`${esc(sorted[0][1].name)} wins`}</h2>${sorted.map(([,p])=>`<p>${esc(p.name)} · ${total(p)} points</p>`).join('')}<button class="btn primary" id="home">back home</button></section>`);$('#home').onclick=landing}
function $(s){return document.querySelector(s)}function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
landing();
